count_odd_bits:count_odd_bits.o
gcc -g -ansi -pedantic -Wall count_odd_bits.c -o count_odd_bits
count_odd_bits.c:count_odd_bits.c count_odd_bits.h
gcc -c -ansi -pedantic -Wall count_odd_bits.c -o count_odd_bits.c
