name: CI - SEFFP Client (CMake + GTest)

on:
  push:
    branches: [ "main" ,"stage3-ci"]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "Secure-Encrypted-File-Transfer-Protocol/vcpkg.json"
          vcpkgDirectory: "${{ github.workspace }}/Secure-Encrypted-File-Transfer-Protocol/vcpkg"

      - name: Configure
        run: >
          cmake -S Secure-Encrypted-File-Transfer-Protocol -B build/seffp
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/Secure-Encrypted-File-Transfer-Protocol/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build/seffp --config Release

      - name: Test
        run: ctest --test-dir build/seffp -C Release --output-on-failure